#
# Makefile for linux/drivers/platform/mcr3000
# mcr3000 Platform-Specific Drivers
#
obj-$(CONFIG_FPGA_LOADER)	+= fpga_loader.o fpga_cs.o
obj-$(CONFIG_FPGAF_INFO)	+= fpgaf_info.o
obj-$(CONFIG_MCR3000_CPLD)	+= cpld_csspi.o
obj-$(CONFIG_OPX_GPIO)		+= opx_gpio.o
obj-$(CONFIG_SAF3000_CLASS)	+= saf3000_class.o
obj-$(CONFIG_CMPC_CPLD)	+= cpld_cmpc.o
