#
# Makefile for linux/drivers/platform/mcr3000
# mcr3000 Platform-Specific Drivers
#
obj-$(CONFIG_FPGA_LOADER)	+= fpga_loader.o
obj-$(CONFIG_MCR3000_CPLD)	+= cpld_csspi.o
obj-$(CONFIG_OPX_GPIO)		+= opx_gpio.o
