.TH "RETOUR CONFIG USINE" 9 2012-08-08 "VERSION 0.1"
.SH NAME
Boot loader \- Retour a la configuration usine sur MIAe
.SH DESCRIPTION
Le switch 
.B retour configuration usine
permet de reinitialiser les parametres d'uboot a leur valeur par defaut.

.SH LE SWITCH CONFIGURATION USINE
Ce switch se situe au dessus de la face arriere. Vu de la face arriere, il se trouve sur la droite de la carte. La position gauche correspond à une demande de retour a la configuration usine. La position droite correspond au mode de fonctionnement normal.

                           
.SH FONCTIONNEMENT NORMAL 
                         
               |
               |
    +-----+    |
    |   | |  <-+---- Switch retour config. usine
    +-----+    |
               |
 --------------+ <-- Face arriere de la carte


                           
.SH RETOUR CONFIGURATION USINE
                         
               |
               |
    +-----+    |
    | |   |  <-+---- Switch retour config. usine
    +-----+    |
               |
 --------------+ <-- Face arriere de la carte


Si au demarrage de la carte le switch
.B retour configuration usine 
se trouve sur la gauche, le secteur contenant la sauvegarde des parametres de
.B uboot
est efface puis la carte se bloque apres avoir affiche un message demandant de remettre le switch en position 
.B fonctionnement normal
et de redemarrer la carte.

